---
title: |
  spmodel: Spatial Modeling in **R** -- Supplementary Material
authors:
  - name: Michael Dumelle
    thanks: Corresponding Author
    department: United States
    affiliation: Environmental Protection Agency
    location: 200 SW 35th St, Corvallis, OR, 97333
    email: Dumelle.Michael@epa.gov
  - name: Matt Higham
    department: Department of Math, Computer Science, and Statistics
    affiliation: St. Lawrence University
    location: 23 Romoda Drive, Canton, NY, 13617
    email: mhigham@stlawu.edu
  - name: Jay M. Ver Hoef
    department: National Oceanic and Atmospheric Administration
    affiliation: Alaska Fisheries Science Center
    location: Marine Mammal Laboratory, Seattle, WA, 98115
    email: jay.verhoef@noaa.gov
abstract: |
  Enter the text of your abstract here.
keywords:
  - Spatial covariance
  - Linear Model
  - Autoregressive model
bibliography: references.bib
biblio-style: unsrt
header-includes: |
  \usepackage{amsmath,amsfonts,amssymb}
  \usepackage{bm, bbm}
output: rticles::arxiv_article
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(prompt=TRUE, echo = TRUE, highlight = FALSE, continue = " + ", comment = "")
options(replace.assign=TRUE, width=90, prompt="R> ")
```

# Covariance Functions

# Estimation

## Likelihood-based Estimation

Minus twice a profiled Gaussian log-likelihood, denoted $-2l(\bm{\theta} | \mathbf{y})$ is given by 
\begin{equation}\label{eq:ml-lik}
  -2l(\bm{\theta} | \mathbf{y}) = \ln{|\mathbf{\Sigma}|} + (\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})^\intercal \mathbf{\Sigma}^{-1} (\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}}) + n \ln{2\pi},
\end{equation}
where $\tilde{\bm{\beta}} = (\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{X})^{-1} \mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{y}$. Minimizing Equation$~$\ref{eq:ml-lik} yields $\bm{\hat{\theta}}_{ml}$, the maximum likelihood estimates for $\bm{\theta}$. Then a closed for solution exists for $\bm{\hat{\beta}}_{ml}$, the maximum likelihood estimates for $\bm{\beta}$: $\bm{\hat{\beta}}_{ml} = \tilde{\bm{\beta}}_{ml}$, where $\tilde{\bm{\beta}}_{ml}$ is $\tilde{\bm{\beta}}$ evaluated at $\bm{\hat{\theta}}_{ml}$. Unfortunately $\bm{\hat{\theta}}_{ml}$ can be badly biased for $\bm{\theta}$ (especially for small sample sizes), which impacts the estimation of $\bm{\beta}$ [@patterson1971recovery]. This bias occurs due to the simultaneous estimation of $\bm{\beta}$ and $\bm{\theta}$ To reduce this bias, restricted maximum likelihood estimation (REML) emerged [@patterson1971recovery; @harville1977maximum; @wolfinger1994computing]. It can be shown that integrating $\bm{\beta}$ out of a Gaussian likelihood yields the restricted Gaussian likelihood used in REML estimation. Minus twice a restricted Gaussian log-likelihood, denoted $-2l_R(\bm{\theta} | \mathbf{y})$ is given by 
\begin{equation}\label{eq:reml-lik}
  -2l_R(\bm{\theta} | \mathbf{y}) = -2l(\bm{\theta} | \mathbf{y})  + \ln{|\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{X}|} - p \ln{2\pi} ,
\end{equation}
where $p$ equals the dimension of $\bm{\beta}$. Minimizing Equation$~$\ref{eq:reml-lik} yields $\bm{\hat{\theta}}_{reml}$, the restricted maximum likelihood estimates for $\bm{\theta}$. Then a closed for solution exists for $\bm{\hat{\beta}}_{reml}$, the restricted maximum likelihood estimates for $\bm{\beta}$: $\bm{\hat{\beta}}_{reml} = \tilde{\bm{\beta}}_{reml}$, where $\tilde{\bm{\beta}}_{reml}$ is $\tilde{\bm{\beta}}$ evaluated at $\bm{\hat{\theta}}_{reml}$.

Generally the overall variance, $\sigma^2$, can be profiled out of Equation$~$\ref{eq:ml-lik} and Equation$~$\ref{eq:reml-lik}. This reduces the number of parameters requiring optimization by one, which can dramatically reduce estimation time. For example, profiling $\sigma^2$ out of Equation$~$\ref{eq:ml-lik} yields
\begin{equation}\label{eq:ml-plik}
  -2l^*(\bm{\theta}^* | \mathbf{y}) = \ln{|\mathbf{\Sigma^*}|} + n\ln[(\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})^\intercal \mathbf{\Sigma}^{-1} (\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})] + n + n\ln{2\pi / n}.
\end{equation}
After finding $\hat{\bm{\theta}}^*_{ml}$ a closed form solution for $\hat{\sigma}^2_{ml}$ exists: $\hat{\sigma}^2_{ml} = [(\mathbf{y} - \mathbf{X} \bm{\tilde{\beta}})^\intercal \mathbf{\Sigma}^{-1} (\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})] / n$. Then $\bm{\hat{\theta}}^*_{ml}$ is combined with $\hat{\sigma}^2_{ml}$ to yield $\bm{\hat{\theta}}_{ml}$ and subsequently $\bm{\hat{\beta}}_{ml}$. A similar result holds for REML estimation. Profiling $\sigma^2$ out of Equation$~$\ref{eq:reml-lik} yields
\begin{equation}\label{eq:reml-plik}
  -2l_R^*(\bm{\theta}^* | \mathbf{y}) = \ln{|\mathbf{\Sigma^*}|} + (n - p)\ln[(\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})^\intercal \mathbf{\Sigma}^{-1} (\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})] + (n - p) + (n - p)\ln2\pi / (n - p).
\end{equation}
After finding $\hat{\bm{\theta}}^*_{reml}$ a closed form solution for $\hat{\sigma}^2_{reml}$ exists: $\hat{\sigma}^2_{reml} = [(\mathbf{y} - \mathbf{X} \bm{\tilde{\beta}})^\intercal \mathbf{\Sigma}^{-1} (\mathbf{y} - \mathbf{X} \tilde{\bm{\beta}})] / (n - p)$. Then $\bm{\hat{\theta}}^*_{reml}$ is combined with $\hat{\sigma}^2_{reml}$ to yield $\bm{\hat{\theta}}_{reml}$ and subsequently $\bm{\hat{\beta}}_{reml}$.

Both ML and REML estimation rely on the an $n \times n$ covariance matrix inverse. Inverting an $n \times n$ matrix is an enormous computational demand that scales cubically with the sample size. For this reason, ML and REML have historically been unfeasible to implement in their standard form with data larger than a few thousand observations. This motivates the use for the big data approaches outlined in Section$~$(INSERT SECTION).

It is worth noting that the inverses themselves are not strictly needed for estimation (or prediction), though at least their square root is needed. In spmodel, calculating this square root requires a Cholesky decomposition, which still scales cubically with the sample size. Computing the Cholesky decomposition, however, is far more computationally efficient than computing the inverse. To see why only the Cholesky decomposition is needed, recall that the Cholesky decomposition of the covariance matrix $\mathbf{\Sigma}$ is $\mathbf{C}\mathbf{C}^\intercal$, where $\mathbf{C}$ is a lower triangular matrix (so $\mathbf{C}\mathbf{C}^\intercal = \mathbf{\Sigma}$). In the ML and REML likelihoods, $\mathbf{\Sigma}^{-1}$ is not needed on its own, only $\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{X}$ and $\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{y}$ are needed. We can rewrite the $\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{X}$ as $\mathbf{X}^\intercal (\mathbf{C}^\intercal)^{-1} \mathbf{C}^{-1} \mathbf{X} = (\mathbf{C}^{-1} \mathbf{X})^\intercal \mathbf{C}^{-1} \mathbf{X}$. Then $\mathbf{C}^{-1} \mathbf{X}$ is efficiently solved by noticing that $\mathbf{C}^{-1} \mathbf{X} = \mathbf{A}$ for some matrix $\mathbf{A}$ implies $\mathbf{X} = \mathbf{C} \mathbf{A}$. This system can be efficiently solved for $\mathbf{A}$ using linear forward solves (forward substitution). Then $\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{X} = \mathbf{A}^\intercal \mathbf{A}$. A similar approach is used to solve $\mathbf{X}^\intercal \mathbf{\Sigma}^{-1} \mathbf{y}$. Still, using Cholesky decomositions is unfeasible for sample sizes larger than a few thousand observations.

## Semivariogram-based Estimation

An alternative approach to likelihood-based estimation is semivariogram-based estimation. The semivariogram of a constant-mean process $\mathbf{y}$ is the expectation of the squared half-difference between two observations $h$ distance units apart. More formally, the semivariogram is denoted $\gamma(h)$ and defined as
\begin{equation}\label{eq:sv}
  \gamma(h) = \text{E}(y_i - y_j)^2 / 2 ,
\end{equation}
where $||y_i - y_j||_2 = h$ (the Euclidean distance). When the process $\mathbf{y}$ is second-order stationary, the semivariogram and covariance function are intimately connected: $\gamma(h) = \text{Cov}(0) - \text{Cov}(h)$, where $\text{Cov}(0)$ is the covariance function evaluated at 0 (which is the overall variance, $\sigma^2$) and $\text{Cov}(h)$is the covariance function evaluated at $h$. Both semivariogram approaches described next are more computationally efficient than ML or REML because their major computational burden (calculations based on pairs) scale the squared sample size (i.e., not the cubed sample size).

### Weighted Least Squares

The empirical semivariogram is a moment-based estimate of the semivariogram denoted by $\hat{\gamma}(h)$ and defined as
\begin{equation}\label{eq:esv}
  \hat{\gamma}(h) = \frac{1}{2|N(h)|} \sum_{N(h)} (y_i - y_j)^2, 
\end{equation}
where $N(h)$ is the set of observations in $\mathbf{y}$ that are $h$ units apart (distance classes) and $|N(h)|$ is the cardinality of $N(h)$ [@cressie1993statistics]. Often the set $N(h)$ contains observations that are $h \pm \alpha$ apart -- this approach is known as "binning" the empirical semivariogram. Typically, only certain $h$ considered when constructing Equation$~$\ref{eq:esv} -- a commonly used cutoff is to ignore $h$ larger than half the maximum distance in the domain. One criticism of the empirical semivariogram is that distance bins and cutoffs tend to be artitrarily chosen (i.e., not chosen according to some statistical criteria).

Equation$~$\eqref{eq:esv} is viewed as the average squared half-distance between two observations in $\mathbf{y}$. @cressie1985fitting proposed estimating $\bm{\theta}$ by minimizing an objective function that involves $\gamma{h}$ and $\hat{\gamma}(h)$ and is based on a weighted least squares criterion. This criterion is defined as
\begin{equation}\label{eq:svwls}
  \sum_i w_i [\hat{\gamma}(h)_i - \gamma(h)_i]^2,
\end{equation}
where $w_i$, $\hat{\gamma}(h)_i$, and $\gamma(h)_i$ are the weights, empirical semivariogram, and semivariogram for the $i$th distance class. @cressie1985fitting recommended setting $w_i = |N(h)| / \gamma(h)_i^2$, which gives more weights to distance classes with more observations ($|N(h)|$) and semivariances at shorter distances ($1 / \gamma(h)_i^2$). The default in spmodel is to use these $w_i$ -- the type of $w_i$ is changed via the \texttt{weights} argument to \texttt{splm()}. Table$~$\ref{tab:weights} contains all $w_i$ available in spmodel. 
\begin{table}\label{tab:weights}
  \centering
  \begin{tabular}{c|c|c}
  \hline
  $w_i$ Name & $w_i$ Form & \texttt{weight = } \\
  Cressie & $|N(h)| / \gamma(h)_i^2$ & \texttt{"cressie"} \\
  Cressie (Denominator) Root & $|N(h)| / \gamma(h)_i$ & \texttt{"cressie-droot"} \\
  Cressie No Pairs & $1 / \gamma(h)_i^2$ & \texttt{"cressie-nopairs"} \\
  Cressie (Denominator) Root No Pairs & $1 / \gamma(h)_i$ & \texttt{"cressie-droot-nopairs"} \\
  Pairs & $|N(h)|$ & \texttt{"pairs"} \\
  Pairs Inverse Distance & $|N(h)| / h^2$ & \texttt{"pairs-invd"} \\
  Pairs Inverse (Root) Distance & $|N(h)| / h$ & \texttt{"pairs-invsd"} \\
  Ordinary Least Squares & 1 & \texttt{ols}
  \end{tabular}
  \caption{spmodel table weights}
\end{table}
Additionally, the number of $N(h)$ classes and maximum distance for $h$ are specified by passing the \texttt{bins} and \texttt{cutoff} arguments to \texttt{splm()} (these arguments are passed via \texttt{...} to \texttt{esv()}). The default value for \texttt{bins} is 15 and the default value for the maximum $h$ is half the maximum distance of the spatial domain's bounding box.

Recall that the semivariogram is defined for a constant-mean process. Generally, $\mathbf{y}$ does not necessarily have a constant mean. So the empirical semivariogram and $\bm{\hat{\theta}}_{wls}$ are typically constructed using the residuals from an ordinary least squares regression of $\mathbf{y}$ on $\mathbf{X}$ -- these residuals are assumed to have mean zero.

### Composite Likelihood

The composite likelihood approach involves constructing a likelihood based on conditional or marginal events for which log-likelihoods are available and then adding together these individual components. Composite likelihoods are attractive because they behave very similar to likelihoods but are easier to handle, both from a theoretical and a computational perspective. @curriero1999composite derive a particular composite likelihood for estimating semivariogram parameters. The negative log of this composite likelihood, denoted $\text{CL}(h)$, is given by
\begin{equation}\label{eq:svcl}
  \text{CL}(h) = \sum_{i = 1}^{n - 1} \sum_{j > i} \left( \frac{(y_i - y_j)^2}{2\gamma(h)} + \ln(\gamma(h)) \right)
\end{equation}
where $\gamma(h)$ is the semivariogram (that depends on parameter vector $\bm{\theta}$). Minimizing Equation$~$\ref{eq:svcl} yields $\bm{\hat{\theta}}_{cl}$, the semivariogram composite likelihood estimates of $\bm{\theta}$.

An advantage of the composite likelihood approach to semivariogram estimation is that it does not require arbitrarily specifying empirial semivariogram bins and cutoffs. It does tend to be more computationally demanding than the weighted least squares, however, as the composite likelihood is constructed from $\binom{n}{2}$ pairs for a sample size $n$, whereas the weighted least squares approach only requires calculating $\binom{|N(h)|}{2}$ pairs for each distance bin $N(h)$. As with the weighted least squares approach, Equation$~$\ref{eq:svcl} requires constant-mean process, so typically the residuals from an ordinary least squares regression of $\mathbf{y}$ on $\mathbf{X}$ are used to estimate $\bm{\theta}$.

# Hypothesis Testing

## The General Linear Hypothesis Test

## Contrasts

# Random Effects

## BLUPs

# References {.unnumbered}
